apiVersion: v1
kind: Service
metadata:
  name: fastapi-app-service
spec:
  selector:
    app: fastapi-app
  type: LoadBalancer
  ports:
  - port: 5055          # El puerto en el que el servicio está disponible externamente, elige uno no utilizado
    targetPort: 5050     # El puerto del contenedor donde está corriendo FastAPI
